# Generated by Django 3.2.3 on 2021-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tours_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='date',
        ),
        migrations.AddField(
            model_name='tours',
            name='date1',
            field=models.DateField(blank=True, null=True, verbose_name='Start day'),
        ),
        migrations.AddField(
            model_name='tours',
            name='date2',
            field=models.DateField(blank=True, null=True, verbose_name='End day'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.CharField(choices=[('mountains', 'MOUNTAINS'), ('lakes_and_rivers', 'LAKES AND RIVERS'), ('gorges', 'GORGES'), ('waterfalls', 'WATERFALLS'), ('hot_springs', 'HOT SPRINGS'), ('equestian', 'EQUESTIAN'), ('cultural', 'CULTURAL')], max_length=16),
        ),
    ]
