# Generated by Django 3.2.3 on 2021-05-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210516_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='point',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.IntegerField(max_length=5),
        ),
    ]
