# Generated by Django 3.2.3 on 2021-05-16 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210516_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='point',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
