# Generated by Django 3.2.3 on 2021-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210516_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='sorting',
            field=models.CharField(blank=True, choices=[('season', 'SEASON'), ('easy', 'EASY'), ('moderate', 'MODERATE'), ('difficult', 'DIFFICULT'), ('extreme', 'EXTREME')], max_length=9, null=True),
        ),
    ]
