# Generated by Django 3.2.3 on 2021-05-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tours_date_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('text', models.CharField(max_length=250)),
                ('date_pub', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
    ]
