# Generated by Django 3.2.3 on 2021-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210517_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendMess',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.CharField(choices=[('mountains', 'MOUNTAINS'), ('lakes and rivers', 'LAKES AND RIVERS'), ('gorges', 'GORGES'), ('waterfalls', 'WATERFALLS'), ('hot springs', 'HOT SPRINGS'), ('equestian', 'EQUESTIAN'), ('cultural', 'CULTURAL')], max_length=16),
        ),
    ]
